{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.27.jar",
          "url": "KoiUpstream-1.0.27.jar",
          "size": 24324,
          "sha512": "1c6e61602ba7054e8278a76194f0a20269d128ddfa095c5f8ff11633b95739834389dffd01d606fa772621f00281b464d002d1deabc53bf3964acde3bf1b5d2d",
          "sha256": "d6956545207197fd23089679e82574168f520ad2c82e3e8ff23f0d1c62c6bdd2",
          "sha1": "02705dd45d4eb61abde08d1182ebe69aeef862a8",
          "md5": "828e66168605c8ac78a0823743a7078f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.27.jar",
          "url": "KoiUpstream-1.0.27.jar",
          "size": 24324,
          "sha512": "1c6e61602ba7054e8278a76194f0a20269d128ddfa095c5f8ff11633b95739834389dffd01d606fa772621f00281b464d002d1deabc53bf3964acde3bf1b5d2d",
          "sha256": "d6956545207197fd23089679e82574168f520ad2c82e3e8ff23f0d1c62c6bdd2",
          "sha1": "02705dd45d4eb61abde08d1182ebe69aeef862a8",
          "md5": "828e66168605c8ac78a0823743a7078f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.27-sources.jar",
          "url": "KoiUpstream-1.0.27-sources.jar",
          "size": 15147,
          "sha512": "572ce9800b06d534a569b7bd9a23257fc1750fd088051cf65885af77cb030a8f5c038a0cfb4eed80bb7384c89218c88c65159c9c486fa3b842574bcabb5bcee5",
          "sha256": "3f0f035c389e0022017fd82b6a9e583bfcfe69a65b9924327add6d63c5a79a4a",
          "sha1": "67650fee85a1d1f97a9b5a3ec49af72f4ef75c9a",
          "md5": "1661f5d74124f5090f0e1a3bb9608903"
        }
      ]
    }
  ]
}
