{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.3.jar",
          "url": "KoiUpstream-1.0.3.jar",
          "size": 36855,
          "sha512": "cec1b6deb50a363716ca86d4a8bf05db0b13e3b362202b5aceea709d2c8549ccf34a66cea1741847e6a0071e5c4c8cd86ab655cc96dd281d6f32ee8d55786439",
          "sha256": "0103422d4cf04a0d7421b2ddf0a697806f50670e8ccd52738a667df3e482a4b4",
          "sha1": "42c3468da79ac8ce91553ede36fa814a73327210",
          "md5": "9c5df1a4599d9c5690789fb66fe4c21b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.3.jar",
          "url": "KoiUpstream-1.0.3.jar",
          "size": 36855,
          "sha512": "cec1b6deb50a363716ca86d4a8bf05db0b13e3b362202b5aceea709d2c8549ccf34a66cea1741847e6a0071e5c4c8cd86ab655cc96dd281d6f32ee8d55786439",
          "sha256": "0103422d4cf04a0d7421b2ddf0a697806f50670e8ccd52738a667df3e482a4b4",
          "sha1": "42c3468da79ac8ce91553ede36fa814a73327210",
          "md5": "9c5df1a4599d9c5690789fb66fe4c21b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.3-sources.jar",
          "url": "KoiUpstream-1.0.3-sources.jar",
          "size": 13504,
          "sha512": "fb61bdb16d53311c1e0ba4238948bb929ea5644d3c2b32b41e8378d39058e42b3f6e35f368b25a6105619eda177d583026143af77cf4b8da0be8ca01c1e5e4ea",
          "sha256": "4d97add3bf2fc28db68c15b205d1a00e8fc78ee6e29d854be2c58cd607f416be",
          "sha1": "ee514c0d8a79922c1c80c1dbcf2eec8ce76f5ec6",
          "md5": "d4168794169e46d4f50cea47db38b7ed"
        }
      ]
    }
  ]
}
