{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "26.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-26.1.0.jar",
          "url": "KoiUpstream-26.1.0.jar",
          "size": 26644,
          "sha512": "97736b63a020271dcfb3f52e35415ce06093ece571d4b14baddced1da809bc8e67dd5253b8c7fdb8ffa121437f5085c05dd1532fc6f0364746f28ca0980518e4",
          "sha256": "b8c6e7bba45d0631d8e230e0539e6d07f83f75b24eaf54f4aa4fdd9993211da4",
          "sha1": "329088176ef0559c0d20fcc9b28555862e436cbf",
          "md5": "cc6d422d4799584e5d9b88cb943e3356"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-26.1.0.jar",
          "url": "KoiUpstream-26.1.0.jar",
          "size": 26644,
          "sha512": "97736b63a020271dcfb3f52e35415ce06093ece571d4b14baddced1da809bc8e67dd5253b8c7fdb8ffa121437f5085c05dd1532fc6f0364746f28ca0980518e4",
          "sha256": "b8c6e7bba45d0631d8e230e0539e6d07f83f75b24eaf54f4aa4fdd9993211da4",
          "sha1": "329088176ef0559c0d20fcc9b28555862e436cbf",
          "md5": "cc6d422d4799584e5d9b88cb943e3356"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-26.1.0-sources.jar",
          "url": "KoiUpstream-26.1.0-sources.jar",
          "size": 16298,
          "sha512": "a13d4be5c220c423d5a140ca7bc6b4155dde3c1e5105b53826dd9b8cf5caf90dc3a5a60153aafcddd87cf2c339bbde3b05ff64f72b57c4693a3abefbe5c27106",
          "sha256": "ebbb54e6ce85a0c0ea8f151bfcf7f27ef453a4ef88f9d6ceb73da8fe7d16897d",
          "sha1": "08ab940a5278eb4566de6d6982a7f43da58000b5",
          "md5": "6ea7195eb72c5d27e8ac507db237671d"
        }
      ]
    }
  ]
}
