{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.11.jar",
          "url": "KoiUpstream-1.0.11.jar",
          "size": 39758,
          "sha512": "9c80c8e32c77e6dd348e96fc889263cc31d779ce6f42ec10ca035c250b8250e2d30637d56af013c5bc08b6109bf79684ddebd4b8be4d7cc4176f1baa63732999",
          "sha256": "0b09ac95064c73292394a7a7da8bd5b72f91832c2a01534de197d0273f7c0bad",
          "sha1": "12506bef9d99bbdb2622c23c160980345224c5f9",
          "md5": "42731c7ef37b9b315b224d39843d55f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.11.jar",
          "url": "KoiUpstream-1.0.11.jar",
          "size": 39758,
          "sha512": "9c80c8e32c77e6dd348e96fc889263cc31d779ce6f42ec10ca035c250b8250e2d30637d56af013c5bc08b6109bf79684ddebd4b8be4d7cc4176f1baa63732999",
          "sha256": "0b09ac95064c73292394a7a7da8bd5b72f91832c2a01534de197d0273f7c0bad",
          "sha1": "12506bef9d99bbdb2622c23c160980345224c5f9",
          "md5": "42731c7ef37b9b315b224d39843d55f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.11-sources.jar",
          "url": "KoiUpstream-1.0.11-sources.jar",
          "size": 14620,
          "sha512": "648e4845de2f32816f0dc73984cb89c7d0771fae7fdca929719d0aca5bc51ba01ef28d139e3edb67414e06080ad329ba6e0b997153dd54e6ee6460bd514c2a48",
          "sha256": "ca5c327683e9f022a3754613824620c5e75f0258c2889dfb67bd6656ef20b90b",
          "sha1": "84d88aca024bb87545084f0404b045f3fa09dc2a",
          "md5": "adf5cdcec49662bb26acd2b38bb9fde2"
        }
      ]
    }
  ]
}
