{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.15.jar",
          "url": "KoiUpstream-1.0.15.jar",
          "size": 44852,
          "sha512": "9d0bbecb6ed06f7bc8473cbf1570a0e78d273a409d396b1e4b850f5c3f8380f3a5478ed9c42fc488e0252e94882707b8388b51da5b5b0dcd4558a187f7d527c2",
          "sha256": "2ae091fac252a4a148b1f4f3958ac1c463766c09f68bb60be697baceeb623a9e",
          "sha1": "82156f8d48014ca55a1b543c0cdeea99b91b4ee9",
          "md5": "d0b9adfb2059595a35d3f6b70db1884c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.15.jar",
          "url": "KoiUpstream-1.0.15.jar",
          "size": 44852,
          "sha512": "9d0bbecb6ed06f7bc8473cbf1570a0e78d273a409d396b1e4b850f5c3f8380f3a5478ed9c42fc488e0252e94882707b8388b51da5b5b0dcd4558a187f7d527c2",
          "sha256": "2ae091fac252a4a148b1f4f3958ac1c463766c09f68bb60be697baceeb623a9e",
          "sha1": "82156f8d48014ca55a1b543c0cdeea99b91b4ee9",
          "md5": "d0b9adfb2059595a35d3f6b70db1884c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.15-sources.jar",
          "url": "KoiUpstream-1.0.15-sources.jar",
          "size": 17814,
          "sha512": "08efb57612775b858ad5e1cc05656f96231f0345035b054c74ca0a0ec3681bd986d00c7d3f649728bde50a0a747830412c7770c3283ad13053a50290e8673e67",
          "sha256": "8867c4934c08432f3f133872215f30bb90adbbbd60babf5cc6a1621b399c5f95",
          "sha1": "6def7cf939ab3603f25fc314e286db4639421dd9",
          "md5": "1ab981ba838035c96b46ab8c66189b80"
        }
      ]
    }
  ]
}
