{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.8.jar",
          "url": "KoiUpstream-1.0.8.jar",
          "size": 39638,
          "sha512": "8e7c8089154064f786f03b6dd772cda915833c68accc286dcd5fb4423488e9ff1bd9e88875c70ccd769641746a588770f8b95a266b2b74a80b2e5164b7c02bee",
          "sha256": "7aa17d7b6d5ba34cd7bb67ffb0ea886276be0c57023787c25b74fa202026271c",
          "sha1": "0c925a4a816f459e06e73371af2bae96c4eb4068",
          "md5": "072dfc5b93cc6f703829b2f162e88c8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.8.jar",
          "url": "KoiUpstream-1.0.8.jar",
          "size": 39638,
          "sha512": "8e7c8089154064f786f03b6dd772cda915833c68accc286dcd5fb4423488e9ff1bd9e88875c70ccd769641746a588770f8b95a266b2b74a80b2e5164b7c02bee",
          "sha256": "7aa17d7b6d5ba34cd7bb67ffb0ea886276be0c57023787c25b74fa202026271c",
          "sha1": "0c925a4a816f459e06e73371af2bae96c4eb4068",
          "md5": "072dfc5b93cc6f703829b2f162e88c8a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.8-sources.jar",
          "url": "KoiUpstream-1.0.8-sources.jar",
          "size": 14546,
          "sha512": "4a865d434a05b9fba212ef2f6f3ae119e8a855064c03ab5be775fe67edeb67ac4f82a67abad07fcf5c0297c2266240b46acc8c34c25db6388b54794ad9d161dc",
          "sha256": "2b82ccf79a753686e2e99b3cb5eadc640d76513dd4ce7f6814b52f08e15c73c4",
          "sha1": "a737d9f93ff2750d16d01dfbf5a0e4bcb24ffb15",
          "md5": "ff433bb735ada9449ef7eb267f0d341e"
        }
      ]
    }
  ]
}
