{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.0.jar",
          "url": "KoiUpstream-1.0.0.jar",
          "size": 37094,
          "sha512": "80ec9631336988f0ea88c2245bc348afee2fb2e8d77b9946f99e734f50b62d669e8eb93d1c0d3835ceda75ccbe8e23d13aa6a96469b26dbcb56a63aa60382627",
          "sha256": "53b042cc8b3de8165ba1a20e525a2e0ba9517336ed8e6abe7921f7035c01f3a4",
          "sha1": "267759c0800d66a84f9972ad6bef18f047a83dd9",
          "md5": "62e1c2246d8b5e7682ff86c00f09602f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "org.littletonrobotics.akit",
          "module": "akit-java",
          "version": {
            "requires": "26.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.0.jar",
          "url": "KoiUpstream-1.0.0.jar",
          "size": 37094,
          "sha512": "80ec9631336988f0ea88c2245bc348afee2fb2e8d77b9946f99e734f50b62d669e8eb93d1c0d3835ceda75ccbe8e23d13aa6a96469b26dbcb56a63aa60382627",
          "sha256": "53b042cc8b3de8165ba1a20e525a2e0ba9517336ed8e6abe7921f7035c01f3a4",
          "sha1": "267759c0800d66a84f9972ad6bef18f047a83dd9",
          "md5": "62e1c2246d8b5e7682ff86c00f09602f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.0-sources.jar",
          "url": "KoiUpstream-1.0.0-sources.jar",
          "size": 13492,
          "sha512": "f8c9e2e01187e03d86157921c98582e443a9565bcc01b27cd495c8ffabbaa960089af4f18d854243157dc32427549202bd6446ea403b66335d6832852c4c244e",
          "sha256": "8549b4fa71110c11e8990ab34ba23bd5e81d73c14597ac89bbd5f809f5d13b3f",
          "sha1": "89fe11c197903b78f45e88c4384067ceecc9395f",
          "md5": "5e0e0da66ad2019107c33528f7b4c229"
        }
      ]
    }
  ]
}
