{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.28.jar",
          "url": "KoiUpstream-1.0.28.jar",
          "size": 25144,
          "sha512": "837bf11870273eb2e0f3c576ac01cb4b0586b66bb7fda6a5a0a38fe46208a5123119e92ee798e67fcd40659d5a167a29217c8dc3dc19b92ff901721d1eb3c862",
          "sha256": "d4557709ee48bfe42c423011f87e0cfc930b5ef78cada6eb9b5840a80e097ec2",
          "sha1": "4db9a7b00049476f30d2dc74f0103e8ad7452bce",
          "md5": "5933f90e8f197fdc14a1d92237495fe6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.28.jar",
          "url": "KoiUpstream-1.0.28.jar",
          "size": 25144,
          "sha512": "837bf11870273eb2e0f3c576ac01cb4b0586b66bb7fda6a5a0a38fe46208a5123119e92ee798e67fcd40659d5a167a29217c8dc3dc19b92ff901721d1eb3c862",
          "sha256": "d4557709ee48bfe42c423011f87e0cfc930b5ef78cada6eb9b5840a80e097ec2",
          "sha1": "4db9a7b00049476f30d2dc74f0103e8ad7452bce",
          "md5": "5933f90e8f197fdc14a1d92237495fe6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.28-sources.jar",
          "url": "KoiUpstream-1.0.28-sources.jar",
          "size": 15503,
          "sha512": "1d61ae06d3bac8ee995554d964951cfe1469a11953af6e5c9165ead92a66158052fb3c1e129b4715d4ae88242560354384089c690d583a69eb19e10465c850aa",
          "sha256": "7b66c4cb2fa17cc335de9ab491006793e9ad2292504c8131f5fec9be4d752a93",
          "sha1": "8fa700786c8f2cccae8e7e85017b0b79c4363a09",
          "md5": "3137062eefc51eb9f9c817a65ebb5e5e"
        }
      ]
    }
  ]
}
