{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.13.jar",
          "url": "KoiUpstream-1.0.13.jar",
          "size": 40922,
          "sha512": "e21ca034abd2ab257283f4f44d4b683106eb90fb39a0c4a38be81f2ef18659b79d34c8a2105f6681d834b3aa7b9cf44c09f336543bb79b76c316e7e9b369763a",
          "sha256": "5d6873f73da32732f807f68505efa5c93ca6ed34ccc921ade5fdec005af7ab8d",
          "sha1": "c35e022410f880fbb2b1bb74f6ee5287cd75ada0",
          "md5": "14fbcafba8839864e275ce2395e14f5f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.13.jar",
          "url": "KoiUpstream-1.0.13.jar",
          "size": 40922,
          "sha512": "e21ca034abd2ab257283f4f44d4b683106eb90fb39a0c4a38be81f2ef18659b79d34c8a2105f6681d834b3aa7b9cf44c09f336543bb79b76c316e7e9b369763a",
          "sha256": "5d6873f73da32732f807f68505efa5c93ca6ed34ccc921ade5fdec005af7ab8d",
          "sha1": "c35e022410f880fbb2b1bb74f6ee5287cd75ada0",
          "md5": "14fbcafba8839864e275ce2395e14f5f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.13-sources.jar",
          "url": "KoiUpstream-1.0.13-sources.jar",
          "size": 15126,
          "sha512": "19ec9ff5f0d33d894bf12dffa1ca6246c4c5ff039e120999739e73244a5e9670d87f8023a7823de8de6d5545094fb4e9cea1d8348c612b7a754ce4eb8b8207d8",
          "sha256": "25053ee412753b90ecafde7f1b9790d005782a15abc60d564549076f2804c3fa",
          "sha1": "d80c10e296b280ecac5eaed10f928420d21d86db",
          "md5": "4f2a76472739012c24d8aee307779168"
        }
      ]
    }
  ]
}
