{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.12.1.jar",
          "url": "KoiUpstream-1.0.12.1.jar",
          "size": 41075,
          "sha512": "83efbc55534d5269dabef3ce09cd4e09974d6838c07508ddb13d65e4aa6e429479b27cc81c4c75104ab43b56080531bca42afc87107f0436e0bd57e063dadd82",
          "sha256": "acbbf43441302519ff863847700e3107318a8ce1d8014bb2c1c7303e458b2728",
          "sha1": "56c5bd2a61ad2858221ebfab29083dd8a7b95987",
          "md5": "bbf9cbc1a07d9414b1b8af22ae65bcd2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.12.1.jar",
          "url": "KoiUpstream-1.0.12.1.jar",
          "size": 41075,
          "sha512": "83efbc55534d5269dabef3ce09cd4e09974d6838c07508ddb13d65e4aa6e429479b27cc81c4c75104ab43b56080531bca42afc87107f0436e0bd57e063dadd82",
          "sha256": "acbbf43441302519ff863847700e3107318a8ce1d8014bb2c1c7303e458b2728",
          "sha1": "56c5bd2a61ad2858221ebfab29083dd8a7b95987",
          "md5": "bbf9cbc1a07d9414b1b8af22ae65bcd2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.12.1-sources.jar",
          "url": "KoiUpstream-1.0.12.1-sources.jar",
          "size": 15067,
          "sha512": "c891efdbf4410e3bc86142d70dededdf7b551df3b7f52855a3518201ca93d3912c39f7f096f840c3f4425a4ac605d4a8ae4ae829ebe0dc7cfa5d6074d847fcde",
          "sha256": "94ddd78a8d0de4fd94e555ff71652294a5ed0dc89561b1aafdc42023fbef5b78",
          "sha1": "52c3beff0cd10862d3d4d7abfa4f2c38d4a76ea0",
          "md5": "21cda146c417fc6ff09a458446181072"
        }
      ]
    }
  ]
}
