{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.9.jar",
          "url": "KoiUpstream-1.0.9.jar",
          "size": 39653,
          "sha512": "cb0ab0c593ab58eb515ff09c021c0e971f73c61fc39e3f96f7b95c6442d01da40826af5b52717baf772380613d4d70d7f7bde367d5513a3e6084ac9c7cb027df",
          "sha256": "6537ea7cfee1db7200dd6aad511f2773ffcc00caec7a4598105ff97c096f5bf6",
          "sha1": "8ec9894925e7cb0431e78470447a1e5f7474f6d8",
          "md5": "53db412fb286d7da77a8099232642f9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.9.jar",
          "url": "KoiUpstream-1.0.9.jar",
          "size": 39653,
          "sha512": "cb0ab0c593ab58eb515ff09c021c0e971f73c61fc39e3f96f7b95c6442d01da40826af5b52717baf772380613d4d70d7f7bde367d5513a3e6084ac9c7cb027df",
          "sha256": "6537ea7cfee1db7200dd6aad511f2773ffcc00caec7a4598105ff97c096f5bf6",
          "sha1": "8ec9894925e7cb0431e78470447a1e5f7474f6d8",
          "md5": "53db412fb286d7da77a8099232642f9c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.9-sources.jar",
          "url": "KoiUpstream-1.0.9-sources.jar",
          "size": 14565,
          "sha512": "972edb77fe98c265bdc83308e9a2d00b98e80168ad5700af318e16e0c45dc0bcd6559589309e67979a507a3f450a6ce447172715670c2784b99f5397755ad5e7",
          "sha256": "03fd9bbd21d50a9566a10d21121f267947383807b0ee4d7b7c62383ac60aee86",
          "sha1": "51aa04ee9ce45ab0c8c48f947df787db9d54391e",
          "md5": "60f0e2549c39e0b7359af9bd375ecd96"
        }
      ]
    }
  ]
}
