{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.26.jar",
          "url": "KoiUpstream-1.0.26.jar",
          "size": 24210,
          "sha512": "03916817ee66ee459eadfaf57fcc2ded185fd062082bcb548b1875623116c033e00b277b885bff3f2f09acc7c8bf64e5ef8c1c92bb3fe8b0cb93620dc27662bf",
          "sha256": "7276b22103ed055adb523f68b5615eaa885baee888be7b3f584cc15304d9d628",
          "sha1": "38e7b97d76664e6e7cc7318536d7e7cab1d35320",
          "md5": "39d40539c32c183ff284d77c01016c4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.26.jar",
          "url": "KoiUpstream-1.0.26.jar",
          "size": 24210,
          "sha512": "03916817ee66ee459eadfaf57fcc2ded185fd062082bcb548b1875623116c033e00b277b885bff3f2f09acc7c8bf64e5ef8c1c92bb3fe8b0cb93620dc27662bf",
          "sha256": "7276b22103ed055adb523f68b5615eaa885baee888be7b3f584cc15304d9d628",
          "sha1": "38e7b97d76664e6e7cc7318536d7e7cab1d35320",
          "md5": "39d40539c32c183ff284d77c01016c4f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.26-sources.jar",
          "url": "KoiUpstream-1.0.26-sources.jar",
          "size": 15259,
          "sha512": "bb06e6eb4eb1a417591f0247e48156ea8617845589debc1a7e4b1331171c38b88f36174b7a1d0f949c370c5c1b92018b3e543196d0444cb348445c80a44c9d78",
          "sha256": "851b885cdb96084abc680baae1ba91176b8f5c2d6ff995461a93a865f756bca2",
          "sha1": "3805fabbf673708e680f1e20b390b68ba0fa1deb",
          "md5": "d22eb011ffad089843bdc30f1f90653c"
        }
      ]
    }
  ]
}
