{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.5.jar",
          "url": "KoiUpstream-1.0.5.jar",
          "size": 38814,
          "sha512": "d4c6065dac3367786e8b162f1dcc36d148a24b84772bd13124e159c258cf8652e6c59a7387f0e741b20bd2af445219377c28f70649b9209a80657b0705599fd4",
          "sha256": "3b97076a4dea2e5803ef102cce8dae1600bfa60a8bf2e9b2762ae7ddc34df886",
          "sha1": "b389ad9640913521aa03e0fd4ba92f24e209b8f7",
          "md5": "af0613f37ba5064ceeb186a7bc118c4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.5.jar",
          "url": "KoiUpstream-1.0.5.jar",
          "size": 38814,
          "sha512": "d4c6065dac3367786e8b162f1dcc36d148a24b84772bd13124e159c258cf8652e6c59a7387f0e741b20bd2af445219377c28f70649b9209a80657b0705599fd4",
          "sha256": "3b97076a4dea2e5803ef102cce8dae1600bfa60a8bf2e9b2762ae7ddc34df886",
          "sha1": "b389ad9640913521aa03e0fd4ba92f24e209b8f7",
          "md5": "af0613f37ba5064ceeb186a7bc118c4c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.5-sources.jar",
          "url": "KoiUpstream-1.0.5-sources.jar",
          "size": 14240,
          "sha512": "1f062b851ee2fc84b3c5fabe9fe354bedc77f3ac7ddfd3dda33c17326d7af3878fe524a75c29939ac3f015f0add855e797d4eb758f228a7b63107fd42dd14457",
          "sha256": "06472697208ae56218a7f8901800e2f9bc950e71a37f3453d1f5705f0ed3391e",
          "sha1": "e3f135dbeef6d548b826556b9c21d9cd71f7569f",
          "md5": "6e2efd1b01c0b1c653be761a0fa0471d"
        }
      ]
    }
  ]
}
