{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.12.jar",
          "url": "KoiUpstream-1.0.12.jar",
          "size": 41029,
          "sha512": "272e528723b0dcca5a3e731400304683aeef92648662ba1cfcbb39917eea73d09b74ae1d328f3f0dca356385dde2c669aa418fe30ad41ab05c224506d057d0df",
          "sha256": "d74768f67a8c8d0de5a2ec047f719995404c637b9f4b7261f5d0478f1fa9499a",
          "sha1": "1e7fe068b56d75f04602bf9f1914f13f89af4c4b",
          "md5": "654bf649e2e767b1f25fca53b0fba57c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.12.jar",
          "url": "KoiUpstream-1.0.12.jar",
          "size": 41029,
          "sha512": "272e528723b0dcca5a3e731400304683aeef92648662ba1cfcbb39917eea73d09b74ae1d328f3f0dca356385dde2c669aa418fe30ad41ab05c224506d057d0df",
          "sha256": "d74768f67a8c8d0de5a2ec047f719995404c637b9f4b7261f5d0478f1fa9499a",
          "sha1": "1e7fe068b56d75f04602bf9f1914f13f89af4c4b",
          "md5": "654bf649e2e767b1f25fca53b0fba57c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.12-sources.jar",
          "url": "KoiUpstream-1.0.12-sources.jar",
          "size": 15049,
          "sha512": "18d2ebd8b7ebc9eee63f1576f2b8c2d691d54464b9f8d6689579953f7fd322d6ab0bdc0f4d1ddce856e86078867171dc14d9b3dce9ee973d944289cefeb32511",
          "sha256": "24ca5d62061fbbde4e41dc25749701ec603d9fad77802511610a4327838d6cfc",
          "sha1": "360343ac5ad6c14da2f902abe708e5733a8066d3",
          "md5": "00de55d8be02d7f1671770d76ac465c6"
        }
      ]
    }
  ]
}
