{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.4.jar",
          "url": "KoiUpstream-1.0.4.jar",
          "size": 38625,
          "sha512": "dd695c50c0091b728a89a2e14a9a23b91a4bbbf10e3d45c0fc1b1ea7ca1dabdb75ef220f37600bdb47b362e1f535252c0bb40b84adca109d0352a6b7ff5d69d0",
          "sha256": "4fc06795d66aba0705f65d20b9d0a1c851a0bc1924156688076558acf3d2fefe",
          "sha1": "428759e81123562dec9e84dd17593f8b306505bb",
          "md5": "2b6f74b302abd0d51d4e6e093ac54a4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.4.jar",
          "url": "KoiUpstream-1.0.4.jar",
          "size": 38625,
          "sha512": "dd695c50c0091b728a89a2e14a9a23b91a4bbbf10e3d45c0fc1b1ea7ca1dabdb75ef220f37600bdb47b362e1f535252c0bb40b84adca109d0352a6b7ff5d69d0",
          "sha256": "4fc06795d66aba0705f65d20b9d0a1c851a0bc1924156688076558acf3d2fefe",
          "sha1": "428759e81123562dec9e84dd17593f8b306505bb",
          "md5": "2b6f74b302abd0d51d4e6e093ac54a4c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.4-sources.jar",
          "url": "KoiUpstream-1.0.4-sources.jar",
          "size": 14097,
          "sha512": "e89ee6a6f02ea405b2f38f42f308a812e4c2be10be9622f558665a5369a0bc90c423ee482e8e6bae752814cd1a80e9c63cb66de93560e6a1e28f778460883f7c",
          "sha256": "94bfcda600f6a9fbae681aefeaef99bfaa832a842c16b69deebbb5e959819466",
          "sha1": "fee971ece86b7bd7b4cc7fe3760f8018b659acaf",
          "md5": "fff42db2a8c6e8b8d48c61775cc5a465"
        }
      ]
    }
  ]
}
