{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-26.0.jar",
          "url": "KoiUpstream-26.0.jar",
          "size": 26162,
          "sha512": "7618136fd895c145042c61cb46806f5a4ff04064a136c0ff67f4e48632571070b9865731f1af2ea0f623e4a7f47931364e322c53534444acbb0bc42d54442e78",
          "sha256": "db35b3427ef8c344434959a477b8bbbb2235ac14ecbe9f002ce573ce5710cdbd",
          "sha1": "9777a63637cf25e6a89bdd3051793b012b722d94",
          "md5": "3ed122d93490ce23afb8a6d70b3e4fac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-26.0.jar",
          "url": "KoiUpstream-26.0.jar",
          "size": 26162,
          "sha512": "7618136fd895c145042c61cb46806f5a4ff04064a136c0ff67f4e48632571070b9865731f1af2ea0f623e4a7f47931364e322c53534444acbb0bc42d54442e78",
          "sha256": "db35b3427ef8c344434959a477b8bbbb2235ac14ecbe9f002ce573ce5710cdbd",
          "sha1": "9777a63637cf25e6a89bdd3051793b012b722d94",
          "md5": "3ed122d93490ce23afb8a6d70b3e4fac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-26.0-sources.jar",
          "url": "KoiUpstream-26.0-sources.jar",
          "size": 15976,
          "sha512": "96c0779f310872eb6ada29930b84befcb7df39c676f8a49f8d08a83a3a9655938e97a59f18d8f4a0aaffa51f23ef977b393072ba6b603e191ddff5934e16bf9e",
          "sha256": "9dbfe94666608220c1a8eb43c5ab7f7c913a8e4e19d0c618d4fd8b2340727396",
          "sha1": "a6d002f28ddc879fd15cbd3a5c1e0fb1d9715197",
          "md5": "1a2dbd6b8ee37ed86a44f5c949c2c8fd"
        }
      ]
    }
  ]
}
