{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.12.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.12.2.2.jar",
          "url": "KoiUpstream-1.0.12.2.2.jar",
          "size": 41301,
          "sha512": "5a9f2f5a02a21702273dcae721dce1460926da9a82ae5d4fdf6eca3bbaa892d12a9544bda2f2d6ae6b471834ec6a260df6d9cb4519f1d68a37daf28d36e0b02d",
          "sha256": "54d64b54d6280de8108c0593d8a3c985a397d202eba9d13e53c5820fd46cf071",
          "sha1": "a071fa692899e27d71afeaaeccd6b88a0168ad41",
          "md5": "331c102eae554b35fb7b8008fd983c2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.12.2.2.jar",
          "url": "KoiUpstream-1.0.12.2.2.jar",
          "size": 41301,
          "sha512": "5a9f2f5a02a21702273dcae721dce1460926da9a82ae5d4fdf6eca3bbaa892d12a9544bda2f2d6ae6b471834ec6a260df6d9cb4519f1d68a37daf28d36e0b02d",
          "sha256": "54d64b54d6280de8108c0593d8a3c985a397d202eba9d13e53c5820fd46cf071",
          "sha1": "a071fa692899e27d71afeaaeccd6b88a0168ad41",
          "md5": "331c102eae554b35fb7b8008fd983c2c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.12.2.2-sources.jar",
          "url": "KoiUpstream-1.0.12.2.2-sources.jar",
          "size": 15192,
          "sha512": "a1a642303aeb73386a61cd3bae116b75fde4113bf4bcc6c5e59c5384da53465338b2dd36496d2d3a073f3dff18e81a7d4ce8d604e802877025c721576127ef09",
          "sha256": "1882c2d6b2146d94c4a78fa435bb0868b4314e17d5bf569b77026f206a00f367",
          "sha1": "f1b5307534c23b6ccf5ef1c75cf68d0f2494d82a",
          "md5": "e0609c3bedaa8c9ffd82505e70905014"
        }
      ]
    }
  ]
}
