{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.6.jar",
          "url": "KoiUpstream-1.0.6.jar",
          "size": 39095,
          "sha512": "5b46c157a96133bc5c5c98966fce2a44172f28177aa300234dc44dd68e736289e90a7f3886d47ce45db491a3616d378e51b18b4261dab4074c15a747ef21b91d",
          "sha256": "811ae3dbf22fec39af4ac29f9d29f62ce9b8b0b33f885b958e61c8b58e2f8e41",
          "sha1": "1feddc2077b474d0fa0f11bafe7aa49c24e11b16",
          "md5": "2417f3f7bfebdbb49424a94abdd2692e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.6.jar",
          "url": "KoiUpstream-1.0.6.jar",
          "size": 39095,
          "sha512": "5b46c157a96133bc5c5c98966fce2a44172f28177aa300234dc44dd68e736289e90a7f3886d47ce45db491a3616d378e51b18b4261dab4074c15a747ef21b91d",
          "sha256": "811ae3dbf22fec39af4ac29f9d29f62ce9b8b0b33f885b958e61c8b58e2f8e41",
          "sha1": "1feddc2077b474d0fa0f11bafe7aa49c24e11b16",
          "md5": "2417f3f7bfebdbb49424a94abdd2692e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.6-sources.jar",
          "url": "KoiUpstream-1.0.6-sources.jar",
          "size": 14301,
          "sha512": "fc835eed11f21f1b18848583fd94fb634b2fc982bdcd8124fcf98720720ed0db2c2d9180140772fb1843fdceb10b2b00015fe13852c4e146fc896e3969ec6318",
          "sha256": "5918be8c5df2fb7baa95555958750810ec29a9c9a5db98640be39b834b491dac",
          "sha1": "ffef5bbddeb584f752895f39a9c671d722487730",
          "md5": "1eee0f5fa0be31ab53f550c4d50282a3"
        }
      ]
    }
  ]
}
