{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.6.jar",
          "url": "KoiUpstream-1.0.6.jar",
          "size": 39431,
          "sha512": "8729b7a95e4cb5420adb521ea2f3674dc64be8006082feedccd0e72d5208793a14c32bb749cbe534da815bb812b08d5b7332275c00be4b32c23efce1b2bf171c",
          "sha256": "8df95bd292693b685aac261d7ae51f8469582a9f3eec7f591cf0b899f2e027be",
          "sha1": "237022bf5deb94826fc412eb1efacd1fe373180d",
          "md5": "1c9035bb81ecde50bcbe5e3d79dc21d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.6.jar",
          "url": "KoiUpstream-1.0.6.jar",
          "size": 39431,
          "sha512": "8729b7a95e4cb5420adb521ea2f3674dc64be8006082feedccd0e72d5208793a14c32bb749cbe534da815bb812b08d5b7332275c00be4b32c23efce1b2bf171c",
          "sha256": "8df95bd292693b685aac261d7ae51f8469582a9f3eec7f591cf0b899f2e027be",
          "sha1": "237022bf5deb94826fc412eb1efacd1fe373180d",
          "md5": "1c9035bb81ecde50bcbe5e3d79dc21d2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.6-sources.jar",
          "url": "KoiUpstream-1.0.6-sources.jar",
          "size": 14444,
          "sha512": "5e19f612d415ee99f90153cb77b8fbc7c22fcc9afdc6834dc0ec5a80da3b9272fa9e1d1d067b2ca10496e755f5bf7e4559e40419a9a0bcc36060c0f827490372",
          "sha256": "9f037fdebf4222765c7cbe1382e2542121cc43597c46f8a7977bf72ab4214014",
          "sha1": "267770c0da4a1c0ba044ef7b1157582523869f51",
          "md5": "bdbbd32d06c920053fb9c3e023bb1fd8"
        }
      ]
    }
  ]
}
