{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.1.jar",
          "url": "KoiUpstream-1.0.1.jar",
          "size": 36736,
          "sha512": "80be430d29e2d7a450ad1239481cbbac3ad94329b86eff7aa2692e032923cbe3167cf8783f2d95767be4b88afcec155b5976fa1bf88c27aa041b8366866ab511",
          "sha256": "8056f8a2c2e8d05aa064cd6bb88d235e8707f5495cb2f713433e4d48c782dd75",
          "sha1": "5c312acf6da224ad69a96e2b590b1667ba5e3f55",
          "md5": "8d6e423608df51655b037a146ce2a8d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.1.jar",
          "url": "KoiUpstream-1.0.1.jar",
          "size": 36736,
          "sha512": "80be430d29e2d7a450ad1239481cbbac3ad94329b86eff7aa2692e032923cbe3167cf8783f2d95767be4b88afcec155b5976fa1bf88c27aa041b8366866ab511",
          "sha256": "8056f8a2c2e8d05aa064cd6bb88d235e8707f5495cb2f713433e4d48c782dd75",
          "sha1": "5c312acf6da224ad69a96e2b590b1667ba5e3f55",
          "md5": "8d6e423608df51655b037a146ce2a8d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.1-sources.jar",
          "url": "KoiUpstream-1.0.1-sources.jar",
          "size": 13435,
          "sha512": "3c8972d80895e7f628a077ebdc1cc7eed8b679e51ebf88f7b4c5d1d87dbf12f5335239b53633eb7cc5e122113285440eba951c7d534b242b04d44b24f97cc3db",
          "sha256": "3bc730427233cdbbc29db7a545c052da62e44655555fee45133e4f74e8edcb03",
          "sha1": "835f81d4d6bcbf7a5bd3ae2fa9f206436e9a3501",
          "md5": "9b05c1259c6796a4e243d7970c022263"
        }
      ]
    }
  ]
}
