{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-26.1.jar",
          "url": "KoiUpstream-26.1.jar",
          "size": 26574,
          "sha512": "62938e66ae016dd0fddfa8fd660a5ce4a79111c1db50e8adde700ea2430ff51e7775d617be3c430879122a1bee91cc7dc2368acd21e28b220f999e0683674140",
          "sha256": "3d31b81c9072a69f62a932517969bae1362a6f4923f35955f64a5ae4b9061eba",
          "sha1": "ffa8320e04177d23a0c32e8df1d066eff4248135",
          "md5": "3f1597f4df3cde9ee89f6475aa2f9e91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-26.1.jar",
          "url": "KoiUpstream-26.1.jar",
          "size": 26574,
          "sha512": "62938e66ae016dd0fddfa8fd660a5ce4a79111c1db50e8adde700ea2430ff51e7775d617be3c430879122a1bee91cc7dc2368acd21e28b220f999e0683674140",
          "sha256": "3d31b81c9072a69f62a932517969bae1362a6f4923f35955f64a5ae4b9061eba",
          "sha1": "ffa8320e04177d23a0c32e8df1d066eff4248135",
          "md5": "3f1597f4df3cde9ee89f6475aa2f9e91"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-26.1-sources.jar",
          "url": "KoiUpstream-26.1-sources.jar",
          "size": 16278,
          "sha512": "971b65d6aa290ff28e065dfb4bf7f566f70183bd8aedcdae198a3619f0b6fec72e9f1c10e2b21e58511f01768b658b529d416d2a1df32f6523cea17ed3b867cb",
          "sha256": "4805a805bda3b75514433bfc30d0a3bef8866e44d2ab642316bd459eb926262d",
          "sha1": "008bb00269ddf53e3dea7a906b257e0dcd752588",
          "md5": "f4ecf6650574efadbff66d1e8273f444"
        }
      ]
    }
  ]
}
