{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.10.jar",
          "url": "KoiUpstream-1.0.10.jar",
          "size": 39755,
          "sha512": "7b8b5be75779150db718c641a23319542020c22b288975454c9bf5f910b5482c1734b0f994ae83ef206e78a9876af22a5da4ab8aa9e260ccbda3e78b28dee51c",
          "sha256": "0c11ec580b7ca9745a4747860f50f7c58584422ae486740077eea3e566b268f1",
          "sha1": "94d14ae9d6e2e4360551ec22aae397162595cbed",
          "md5": "b120166a916a6d461fc64a4c230be3c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.10.jar",
          "url": "KoiUpstream-1.0.10.jar",
          "size": 39755,
          "sha512": "7b8b5be75779150db718c641a23319542020c22b288975454c9bf5f910b5482c1734b0f994ae83ef206e78a9876af22a5da4ab8aa9e260ccbda3e78b28dee51c",
          "sha256": "0c11ec580b7ca9745a4747860f50f7c58584422ae486740077eea3e566b268f1",
          "sha1": "94d14ae9d6e2e4360551ec22aae397162595cbed",
          "md5": "b120166a916a6d461fc64a4c230be3c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.10-sources.jar",
          "url": "KoiUpstream-1.0.10-sources.jar",
          "size": 14620,
          "sha512": "dc3e1cf1feb5dc4570b59d5e1c3e7bc980e938f480b7e2179e77ee83b45cf2b74c3eff16c1278139a06e048cd3ef7685fda633aad98b5700de2f45db7b4b980e",
          "sha256": "0b10fc6b52e8f161573064351b6623a87181fc31ad0d7de689f5e94abbb354a2",
          "sha1": "a5ecb981afba879fbb210cb1e8ea7563fea4a8ae",
          "md5": "b9493aecdaa0a791794741372a873e3a"
        }
      ]
    }
  ]
}
