{
  "formatVersion": "1.1",
  "component": {
    "group": "team6230",
    "module": "KoiUpstream",
    "version": "1.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.14.jar",
          "url": "KoiUpstream-1.0.14.jar",
          "size": 41031,
          "sha512": "5ccc0bfc99f728cbfe3c70faae9194099c815b4c6cce75311041a03436b2b228834a56c58f20804d2b77a4aaac08c237d02e61c65a724300e221b4ef08621e5f",
          "sha256": "060f2072bd2fba5d01fae6eb739b43d97bc7306ee803c89a7ad946de6ccb8eed",
          "sha1": "b4fdea7549c1cb1c0a40d5760a0a2095de503f07",
          "md5": "31e0df4e48e87dec36b81ce48fea7579"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "KoiUpstream-1.0.14.jar",
          "url": "KoiUpstream-1.0.14.jar",
          "size": 41031,
          "sha512": "5ccc0bfc99f728cbfe3c70faae9194099c815b4c6cce75311041a03436b2b228834a56c58f20804d2b77a4aaac08c237d02e61c65a724300e221b4ef08621e5f",
          "sha256": "060f2072bd2fba5d01fae6eb739b43d97bc7306ee803c89a7ad946de6ccb8eed",
          "sha1": "b4fdea7549c1cb1c0a40d5760a0a2095de503f07",
          "md5": "31e0df4e48e87dec36b81ce48fea7579"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "KoiUpstream-1.0.14-sources.jar",
          "url": "KoiUpstream-1.0.14-sources.jar",
          "size": 15131,
          "sha512": "37f37ed12baae8aea73c8868c13b7bfb4d3bc6d5cb05d5282bea69c4706a0a6ac194eb759073b23f487b9cfab693dd003623946d06297c87423f43ddad171927",
          "sha256": "cd8b2111334e0ad9abbb907e62a1674aa6fe3c5a945ab2d3b59516b02d9a732c",
          "sha1": "72c3220deff118e396df328bb15a305b22980c1c",
          "md5": "9937e2cd45e59d1814a0f320b05bd3b0"
        }
      ]
    }
  ]
}
